---
name: OB release
author: https://github.com/qcastel
description: Release our java libraries for open banking
branding:
  color: blue
  icon: unlock
inputs:
  release-branch-name:
    description: Filter the branch to execute the release on
    required: false

  gpg-enabled:
    description: Enable gpg signing
    required: false
    default: false
  gpg-key:
    description: The GPG key
    required: false
  gpg-key-id:
    description: The GPG key ID
    required: false

  git-release-bot-email:
    description: The git user email for committing the release
    required: true
  git-release-bot-name:
    description: The git user name for committing the release
    required: true
  maven-args:
    description: The maven arguments for the release
    required: false
    default: ""
  maven-local-repo-path:
    description: The maven local repository path
    required: false
    default: $M2_HOME/repository
  maven-repo-server-id:
    description: Maven server repository id to push the artefacts to
    required: true
  maven-repo-server-password:
    description: Maven server repository password
    required: true
  maven-repo-server-username:
    description: Maven server repository username
    required: true

  access-token:
    description:
      Github access token.
      https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - release.sh
  env:
    RELEASE_BRANCH_NAME: ${{ inputs.release-branch-name }}

    GPG_ENABLED: ${{ inputs.gpg-enabled }}
    GPG_KEY: ${{ inputs.gpg-key }}
    GPG_KEY_ID: ${{ inputs.gpg-key-id }}

    MAVEN_ARGS: ${{ inputs.maven-args }}
    MAVEN_LOCAL_REPO_PATH: ${{ inputs.maven-local-repo-path }}
    MAVEN_REPO_SERVER_ID: ${{ inputs.maven-repo-server-id }}
    MAVEN_REPO_SERVER_PASSWORD: ${{ inputs.maven-repo-server-password }}
    MAVEN_REPO_SERVER_USERNAME: ${{ inputs.maven-repo-server-username }}

    GIT_RELEASE_BOT_EMAIL: ${{ inputs.git-release-bot-email }}
    GIT_RELEASE_BOT_NAME: ${{ inputs.git-release-bot-name }}

    GITHUB_ACCESS_TOKEN: ${{ inputs.access-token }}
