---
blank_issues_enabled: true
contact_links:
  - name: General MIRSG issue
    url: https://github.com/UCL-MIRSG/MIRSG/issues/new/choose
    about: >-
      If your issue is a general MIRSG issue rather than this repo specific.
