name: "Repository Request"
description: "Request a new GitHub repository with our teddy bear helper!"
title: "[Repo Request] Your Repository Name"
labels: ["repo-request"]
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
          <h1>🧸 New Repository Request</h1>
          <p>Let our teddy bear help you create a new repository!</p>
        </div>

  - type: input
    id: repo_name
    attributes:
      label: "Repository Name"
      description: "What should we name your new repository?"
      placeholder: "my-awesome-project"
    validations:
      required: true

  - type: dropdown
    id: default_branch
    attributes:
      label: "Default Branch"
      description: "Select the default branch name"
      options:
        - "main"
        - "develop"
        - "trunk"
    validations:
      required: true

  - type: dropdown
    id: include_readme
    attributes:
      label: "Include README?"
      description: "Should we include a starter README file?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Tell us about your project"
      placeholder: "This repository will contain..."
    validations:
      required: false

  - type: checkboxes
    id: options
    attributes:
      label: "Extra Features"
      description: "Select any additional options"
      options:
        - label: "Add .gitignore file"
          required: false
        - label: "Add MIT License"
          required: false
        - label: "Enable GitHub Discussions"
          required: false
        - label: "Enable GitHub Projects"
          required: false

  - type: markdown
    attributes:
      value: |
        **🐻 What happens next?**  
        1. Our teddy bot will process your request  
        2. You'll receive a notification when ready  
        3. Your new repo will appear in our organization  
        Need help? Contact [our bears](mailto:support@example.com)
