---
name: Work
description: Track any work to be done
labels:
  - work
projects:
  - UCL-MIRSG/3
body:
  - type: markdown
    attributes:
      value: >-
        Add any new work item - this may be a feature, story, requirement,
        service request or general task.
  - type: textarea
    id: short_description
    attributes:
      label: Short Description
      description: Briefly summarise the work to be done.
      placeholder: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: >-
        What must be done for this work to be considered complete? These can be
        a checklist of tasks or a description of the expected outcome. If
        complex, consider creating new issues for each task and linking them
        here.
      placeholder: "- [ ] e.g. x is done in y way so that z can be achieved"
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: >-
        What other work does this depend on? Enter the github issue number in
        the form `- [ ] #356` or `- [ ] UCL-MIRSG/repo-name#243` to make a
        checklist.
      placeholder: "- [ ] #356"
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide any additional information that may be useful.
      placeholder:
        e.g. Additional context, links to documentation and diagrams, etc.
    validations:
      required: false
