---
name: Add Issues to Project
description: Add issues to the GitHub project board

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  project-url:
    description: URL of the project board to add issues to
    default: https://github.com/orgs/UCL-MIRSG/projects/3

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Get project data
      uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ steps.generate-token.outputs.token }}
