name: Create Team PR

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Team Details
        id: extract
        run: |
          # Extract issue body from GitHub event
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Debugging: Print the issue body
          echo "Issue Body:"
          echo "$ISSUE_BODY"
          
          # Extract all fields using more precise parsing
          TEAM_NAME=$(echo "$ISSUE_BODY" | awk '/^### Team Name$/{getline; getline; print}' | sed 's/[`]//g' | xargs)
          VISIBILITY=$(echo "$ISSUE_BODY" | awk '/^### Visibility$/{getline; getline; print}' | sed 's/[`]//g' | xargs)
          PURPOSE=$(echo "$ISSUE_BODY" | awk '/^### Purpose$/{getline; getline; print}' | sed 's/[`]//g' | xargs)
          MAINTAINERS=$(echo "$ISSUE_BODY" | awk '/^### Maintainers \(comma-separated\)$/{getline; getline; print}' | sed 's/[`]//g' | xargs)
          
          # Debugging: Print extracted values
          echo "Extracted Values:"
          echo "Team Name: '$TEAM_NAME'"
          echo "Visibility: '$VISIBILITY'"
          echo "Purpose: '$PURPOSE'"
          echo "Maintainers: '$MAINTAINERS'"
          
          # Validate team name format
          if [[ ! "$TEAM_NAME" =~ ^TEAM-[a-zA-Z0-9_-]+$ ]]; then
            echo "::error::Team name not found or invalid: '$TEAM_NAME'"
            exit 1
          fi
          
          # Set default values if empty
          VISIBILITY=${VISIBILITY:-Visible}
          PURPOSE=${PURPOSE:-Team created via automation}
          MAINTAINERS=${MAINTAINERS:-none}
          
          # Store extracted values
          echo "$TEAM_NAME" > team-name.txt
          echo "team_name=$TEAM_NAME" >> "$GITHUB_ENV"
          echo "visibility=$VISIBILITY" >> "$GITHUB_ENV"
          echo "purpose=$PURPOSE" >> "$GITHUB_ENV"
          echo "maintainers=$MAINTAINERS" >> "$GITHUB_ENV"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Add team: ${{ env.team_name }}"
          title: "Create team: ${{ env.team_name }}"
          body: |
            ### Team Creation Request
            **Team Name:** ${{ env.team_name }}
            **Visibility:** ${{ env.visibility }}
            **Purpose:** ${{ env.purpose }}
            **Maintainers:** ${{ env.maintainers }}
            
            Generated from issue #${{ github.event.issue.number }}
          branch: "team-request/${{ github.event.issue.number }}"
          labels: "team-creation"
          paths: |
            team-name.txt
