name: Create Team PR
on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Validate Issue
        id: validate
        run: |
          if ! echo '${{ toJSON(github.event.issue.labels) }}' | grep -q 'team-request'; then
            echo "::error::Missing team-request label"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if [[ ! "${{ github.event.issue.title }}" =~ ^'[Team]' ]]; then
            echo "::error::Title must start with '[Team]'"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "valid=true" >> $GITHUB_OUTPUT

      - name: Create PR
        if: steps.validate.outputs.valid == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add team request for ${{ github.event.issue.title }}"
          title: "Team Request: ${{ github.event.issue.title }}"
          body: |
            ### Team Creation Request
            **From Issue #${{ github.event.issue.number }}**
            
            ```yaml
            ${{ github.event.issue.body }}
            ```
          branch: "team-request/${{ github.event.issue.number }}"
          labels: "team-creation"
          base: "main"  # Change to your default branch
          delete-branch: true  # Clean up after merge
