name: Create Team PR
on:
  issues:
    types: [opened, edited]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Issue
        id: validate
        run: |
          if ! echo '${{ toJSON(github.event.issue.labels) }}' | grep -q 'team-request'; then
            echo "::error::Missing team-request label"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Additional validation...

      - name: Create PR
        if: steps.validate.outputs.valid == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add team request for ${{ github.event.issue.title }}"
          title: "Team Request: ${{ github.event.issue.title }}"
          body: "Automated from issue #${{ github.event.issue.number }}"
          branch: "team-request/${{ github.event.issue.number }}"
          labels: "team-creation"
