name: Create Team PR
on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Team Name
        id: extract
        run: |
          # Extract issue body from GitHub event
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Extract team name using awk and trim spaces
          TEAM_NAME=$(echo "$ISSUE_BODY" | awk '/^### Team Name/ {getline; print}' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

          # Ensure it matches TEAM- pattern
          if [[ ! "$TEAM_NAME" =~ ^TEAM-[a-zA-Z0-9_-]+$ ]]; then
            echo "::error::Team name not found or invalid: '$TEAM_NAME'"
            exit 1
          fi

          # Store extracted team name and set output
          echo "$TEAM_NAME" > team-name.txt
          echo "team_name=$TEAM_NAME" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Add team: ${{ steps.extract.outputs.team_name }}"
          title: "Create team: ${{ steps.extract.outputs.team_name }}"
          body: |
            ### Team Creation Request
            **Team Name:** `${{ steps.extract.outputs.team_name }}`
            
            Generated from issue #${{ github.event.issue.number }}
          branch: "team-request/${{ github.event.issue.number }}"
          labels: "team-creation"
          paths: |
            team-name.txt
