name: Create Team PR
on:
  issues:
    types: [opened, edited]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Issue
        id: validate
        run: |
          # Check label
          if ! echo '${{ toJSON(github.event.issue.labels) }}' | grep -q 'team-request'; then
            echo "::error::Missing team-request label"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check title format
          if [[ ! "${{ github.event.issue.title }}" =~ ^'[Team] TEAM-' ]]; then
            echo "::error::Title must be '[Team] TEAM-Name'"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "valid=true" >> $GITHUB_OUTPUT

      - name: Create PR
        if: steps.validate.outputs.valid == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Team Request: ${{ github.event.issue.title }}"
          body: |
            ### Team Creation Request
            **From Issue #${{ github.event.issue.number }}**
            
            ```yaml
            ${{ github.event.issue.body }}
            ```
          branch: "team-request/${{ github.event.issue.number }}"
          labels: "team-creation"
